### ISSUE TITLE
`lungmap_utils.client.get_image_set_candidates` bug

### ISSUE THREAD

**Issue by benneely** [duke-lungmap-team/lungmap-utils#2]
Currently running, `lungmap_utils.client.get_image_set_candidates` errors out. With the backend ontology constantly changing, I wonder if the rest api is more stable and a better option (#1)?

**Comment by whitews** [comment]
Don't believe the back-end has changed this time, only that some images have bad source URLs. Again, the REST API requires token authentication that prohibits this library from using it. If we make a token available via this library it defeats the purpose of having the authentication...don't know what their rationale is for having it, but that's not up to us.
